name: Setup Node
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9.11.0
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
        cache-dependency-path: "pnpm-lock.yaml"
    - run: npm run setup
      shell: bash
    - run: pnpm i
      shell: bash
