name: Chromatic

on:
  push:

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup-node

      - name: Run Chromatic
        uses: chromaui/action@v1
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
