name: Chromatic

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      uses: ./.github/actions/setup-node
      uses: chromaui/action@latest  
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
