name: ci

on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - src/**
      - .github/workflows/ci.yml
  push:
    branches:
      - main
    paths:
      - package.json
      - src/**
      - .github/workflows/ci.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm lint
